# Generated by Django 4.2.3 on 2023-07-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='user',
            new_name='bidder',
        ),
    ]
